module.exports = {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
    './src/content/**/*.{js,jsx,md}',
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Bebas Neue', 'Anton', 'sans-serif'],
        body: ['Inter', 'Helvetica Neue', 'Arial', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        ink: '#111111',
        canvas: '#ffffff',
        'soft-cloud': '#f5f5f5',
        charcoal: '#39393b',
        ash: '#4b4b4d',
        mute: '#707072',
        stone: '#9e9ea0',
        hairline: '#cacacb',
        'hairline-soft': '#e5e5e5',
        sale: '#d30005',
        success: '#007d48',
        info: '#1151ff',
        border: '#e5e5e5',
        ring: '#111111',
        background: '#ffffff',
        foreground: '#111111',
        primary: {
          DEFAULT: '#111111',
          foreground: '#ffffff',
        },
        muted: {
          DEFAULT: '#f5f5f5',
          foreground: '#707072',
        },
      },
      borderRadius: {
        none: '0px',
        sm: '18px',
        md: '24px',
        lg: '30px',
        full: '9999px',
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '0.9', fontWeight: '500', letterSpacing: '0' }],
        'display-lg': ['64px', { lineHeight: '0.9', fontWeight: '500', letterSpacing: '0' }],
        'display-md': ['48px', { lineHeight: '1', fontWeight: '500', letterSpacing: '0' }],
        'heading-xl': ['40px', { lineHeight: '1.1', fontWeight: '500', letterSpacing: '-0.01em' }],
        'heading-lg': ['28px', { lineHeight: '1.2', fontWeight: '500', letterSpacing: '0' }],
        'heading-md': ['20px', { lineHeight: '1.3', fontWeight: '500', letterSpacing: '0' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '0' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '0' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '0' }],
        'button-md': ['15px', { lineHeight: '1', fontWeight: '500', letterSpacing: '0' }],
        'button-sm': ['13px', { lineHeight: '1', fontWeight: '500', letterSpacing: '0' }],
        'caption-md': ['14px', { lineHeight: '1.5', fontWeight: '500', letterSpacing: '0' }],
        'caption-sm': ['12px', { lineHeight: '1.5', fontWeight: '500', letterSpacing: '0' }],
        'label-xs': ['11px', { lineHeight: '1', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      spacing: {
        'section': '64px',
        'section-lg': '96px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
